language: php

php:
  - 5.3

env:
  - DB=mysql

before_script:
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/PHPUnit_Selenium
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE tokilearning;'; fi"
  - echo "<?php
    return array(
        'connectionString' => 'mysql:host=localhost;dbname=tokilearning',
        'emulatePrepare' => true,
        'username' => 'travis',
        'password' => '',
        'charset' => 'utf8',
    );" > protected/config/application/database.php
  - /usr/bin/yes | php protected/yiic migrate

script:
  - phpunit --configuration protected/tests/phpunit.xml protected/tests/unit/
