<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
    <head profile="http://gmpg.org/xfn/11">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="description" content="" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/screen.css" type="text/css" media="screen,projection" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/print.css" type="text/css" media="print" />
        <!--[if IE 6]>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/ie.css" type="text/css" media="screen,projection" />
	<![endif]-->
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/styles/default.css" type="text/css" media="screen,projection" />	<!--[if IE 6]>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie6.css" type="text/css" />
	<![endif]-->
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/layouts/2c-r-fixed.css" type="text/css" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/user.css" type="text/css" media="screen,projection" />
		<link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.ico" type="image/x-icon" /> 
        <!-- Generated by Arras Theme -->
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>
    <body class="home blog logged-in layout-2c-r-fixed style-default no-js">
        <div id="header">
            <div id="branding" class="clearfix">
                <div class="logo clearfix">
                    <h1 class="site-name"><?php echo CHtml::link(Yii::app()->name, array('/home')) ?></h1>
                    <h2 class="site-description"><?php echo Yii::app()->params->tagline; ?></h2>
                </div>
            </div><!-- #branding -->

        </div><!-- #header -->
        <div id="wrapper">
            <div id="main" class="clearfix">
                <?php echo $content; ?>
            </div><!-- #main -->
            <?php $this->renderPartial('application.views.layouts._footer'); ?>
        </div><!-- #wrapper -->
    </body>
</html>
