<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:og="http://opengraphprotocol.org/schema/"
	xmlns:fb="http://www.facebook.com/2008/fbml"
	dir="ltr" 
	lang="en-US">
    <head profile="http://gmpg.org/xfn/11">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="google-site-verification" content="pMuTARYm7HBtwTKS_EvzcSQWciUNgChrKsLqhIrIgcA" />
        <meta name="language" content="<?php echo Yii::app()->language ?>"/>
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/screen.css" type="text/css" media="screen,projection" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/print.css" type="text/css" media="print" />
        <!--[if IE 6]>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/ie.css" type="text/css" media="screen,projection" />
	<![endif]-->
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/styles/default.css" type="text/css" media="screen,projection" />	<!--[if IE 6]>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie6.css" type="text/css" />
	<![endif]-->
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/layouts/2c-r-fixed.css" type="text/css" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/user.css" type="text/css" media="screen,projection" />
        <link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.ico" type="image/x-icon" />
        <?php Yii::app()->clientScript->registerLinkTag('alternate', 'application/rss+xml', $this->createAbsoluteUrl('/feed')); ?>
        <title><?php echo CHtml::encode(Yii::app()->name . " - " . $this->pageTitle); ?></title>
        <!-- Generated by Arras Theme -->
        <?php if ((!IPChecker::isInITB()) && (!IPChecker::isLocal())): ?>
            <script type="text/javascript">

                var _gaq = _gaq || [];
                _gaq.push(['_setAccount', 'UA-7168160-11']);
                _gaq.push(['_setDomainName', '.tokilearning.org']);
                _gaq.push(['_trackPageview']);

                (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                })();

            </script>
        <?php endif; ?>
        </head>
        <body class="home blog logged-in layout-2c-r-fixed style-default no-js">
            <div id="header">
                <div id="branding" class="clearfix">
                <?php echo CHtml::image(Yii::app()->request->baseUrl . '/images/logo-toki-40.png', '', array('style' => 'float:left;margin: 20px 0px 0px 15px;')); ?>
                <div class="logo clearfix">
                    <h1 class="site-name"><?php echo CHtml::link(Yii::app()->name, array('/home')) ?></h1>
                    <h2 class="site-description"><?php echo Yii::app()->params->tagline; ?></h2>
                </div>
                <div id="top-nav">
                    <?php
                    $this->widget('zii.widgets.CMenu', array(
                        'items' => array(
                            array('label' => Yii::t('menu', 'Halo, ') . Yii::app()->user->getRecord()->full_name),
                            array('label' => Yii::t('menu', 'Keluar'), 'url' => array('/account/signout'))),
                    ));
                    ?>
                </div>
            </div><!-- #branding -->

        </div><!-- #header -->
        <div id="nav">
            <div id="nav-content" class="clearfix">
                <?php
                    $this->widget('zii.widgets.CMenu', array(
                        'items' => array(
                            array('label' => Yii::t('menu', 'Laman'), 'url' => array('/home')),
                            array('label' => Yii::t('menu', 'TOKI'), 'url' => 'http://www.toki.or.id'),
                        	array('label' => Yii::t('menu', 'Diskusi'), 'url' => 'http://on.fb.me/f2ELxs'),
						),
                        'htmlOptions' => array('class' => 'sf-menu menu clearfix'),
						'encodeLabel' => false,
                    ));
                    $this->widget('application.components.widgets.languagechooser.LanguageChooser');
                ?>
                    <ul class="quick-nav clearfix">
                        <div id="searchbar">
                            <form method="get" class="searchform clearfix" action="">
                                <input type="text" value="Search..." name="s" class="s" onfocus="this.value=''" />
                                <input type="submit" class="searchsubmit" value="Search" title="Search Test" />
                            </form>
                        </div>
                    </ul>
                </div><!-- #nav-content -->
            </div><!-- #nav -->
            <div id="wrapper">
                <div id="main" class="clearfix">
                <?php echo $content; ?>
                </div><!-- #main -->
            <?php $this->renderPartial('application.views.layouts._footer'); ?>
        </div><!-- #wrapper -->
    </body>
</html>
