<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
    <head profile="http://gmpg.org/xfn/11">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/screen.css" type="text/css" media="screen,projection" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/print.css" type="text/css" media="print" />
        <!--[if IE 6]>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/blueprint/ie.css" type="text/css" media="screen,projection" />
	<![endif]-->
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/styles/default.css" type="text/css" media="screen,projection" />	<!--[if IE 6]>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie6.css" type="text/css" />
	<![endif]-->
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/layouts/2c-r-fixed.css" type="text/css" />
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/arrastheme/user.css" type="text/css" media="screen,projection" />
		<link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/favicon.ico" type="image/x-icon" /> 
        <title><?php echo CHtml::encode(Yii::app()->name ." - ". $this->pageTitle); ?></title>
        <!-- Generated by Arras Theme -->
        <?php if (!defined('YII_LOCAL')):?>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-7168160-10']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
        <?php endif;?>
    </head>
    <body class="home blog logged-in layout-2c-r-fixed style-default no-js">
    <?php echo $content; ?>
    </body>
</html>